// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8Gd9GTsSwI2gNXMPaLbnS5w_HU4dUyhQ',
    appId: '1:1069377112063:web:983d7ae41b658cf300c9ca',
    messagingSenderId: '1069377112063',
    projectId: 'grassportapp-7ccb1',
    authDomain: 'grassportapp-7ccb1.firebaseapp.com',
    storageBucket: 'grassportapp-7ccb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAd6EioRAywoRPJlBwE7JumLWA5cSb8cg',
    appId: '1:1069377112063:android:3757816a6845e95c00c9ca',
    messagingSenderId: '1069377112063',
    projectId: 'grassportapp-7ccb1',
    storageBucket: 'grassportapp-7ccb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAtpVeEsrhCw7U7mmRgCgd5JXqE15aY6A',
    appId: '1:1069377112063:ios:c193cf327db0590d00c9ca',
    messagingSenderId: '1069377112063',
    projectId: 'grassportapp-7ccb1',
    storageBucket: 'grassportapp-7ccb1.appspot.com',
    iosBundleId: 'com.example.grassportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAtpVeEsrhCw7U7mmRgCgd5JXqE15aY6A',
    appId: '1:1069377112063:ios:123722e10f4e361400c9ca',
    messagingSenderId: '1069377112063',
    projectId: 'grassportapp-7ccb1',
    storageBucket: 'grassportapp-7ccb1.appspot.com',
    iosBundleId: 'com.example.grassportApp.RunnerTests',
  );
}
